### ISSUE TITLE
github actions: pages build and deployment

### ISSUE THREAD

**Issue by lv123123long** [moeyua/astro-theme-typography#131]
I came across an error and asked for your help, if you could look at it, thank you very much.

blog url: https://github.com/lv123123long/lv123123long.github.io

ERROR:------------------------------------------------below--------------------------------------------------------------------------------
Build with Jekyll

To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
YAML Exception reading /github/workspace/src/components/Disqus.astro: (<unknown>): mapping values are not allowed in this context at line 3 column 13 
YAML Exception reading /github/workspace/src/components/Twikoo.astro: (<unknown>): mapping values are not allowed in this context at line 3 column 7 
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid YAML front matter in /github/workspace/src/components/Giscus.astro
Error:  Logging at level: debug GitHub Pages: github-pages v232 GitHub Pages: jekyll v3.10.0 Theme: jekyll-theme-primer Theme source: /usr/local/bundle/gems/jekyll-theme-primer-0.6.0 Requiring: jekyll-github-metadata Requiring: jekyll-seo-tag Requiring: jekyll-coffeescript Requiring: jekyll-commonmark-ghpages Requiring: jekyll-gist Requiring: jekyll-github-metadata Requiring: jekyll-paginate Requiring: jekyll-relative-links Requiring: jekyll-optional-front-matter Requiring: jekyll-readme-index Requiring: jekyll-default-layout Requiring: jekyll-titles-from-headings GitHub Metadata: Initializing... Source: /github/workspace/. Destination: /github/workspace/./_site Incremental build: disabled. Enable with --incremental Generating...

**Comment by moeyua** [comment]
Maybe this can help you: https://github.com/withastro/astro/issues/6830
