### ISSUE TITLE
代码块高亮不知道如何取消掉底色

### ISSUE THREAD

**Issue by sailor0913** [moeyua/astro-theme-typography#138]
![image](https://github.com/user-attachments/assets/dcca72fa-6507-4bce-8b4b-1b176c2f40d2)

所有代码都有一个如图的底色，求教该如何取消掉？

**Comment by moeyua** [comment]
你好，这个问题确认是 BUG，已经在最新的提交被修复～

**Comment by sailor0913** [comment]
> 你好，这个问题确认是 BUG，已经在最新的提交被修复～

你好，似乎还是不行？我更新了主题，代码仍然是有底色

**Comment by sailor0913** [comment]
是我的问题，不知道为什么拉取最新的主题没有成功，用的还是原先的主题仓库所以导致还是看到老样子。

自己手动按照你的方法修改了源代码，已经可以了

感谢作者维护这么好看的博客主题！

**Comment by moeyua** [comment]
> 是我的问题，不知道为什么拉取最新的主题没有成功，用的还是原先的主题仓库所以导致还是看到老样子。
> 
> 自己手动按照你的方法修改了源代码，已经可以了
> 
> 感谢作者维护这么好看的博客主题！

不客气！
