### ISSUE TITLE
Duplicate formula rendering in LaTeX

### ISSUE THREAD

**Issue by saxicek** [moeyua/astro-theme-typography#176]
When you check https://astro-theme-typography.vercel.app/posts/latex/, formulas are duplicated - they are present once with math-like rendering with indexes and then with simplified notation. Is that expected?

![obrazek](https://github.com/user-attachments/assets/d19c4426-93a8-4a33-bcf9-5ec24d2dded4)

**Comment by moeyua** [comment]
Yes, this is because the config has LaTeX rendering turned off by default. After modifying it in the configuration file, it can be displayed normally.

```ts
latex: {
  katex: true,
},
```
