### ISSUE TITLE
[Performance] 代码和超链接配合使用问题

### ISSUE THREAD

**Issue by condorheroblog** [moeyua/astro-theme-typography#2]
我观察到超链接是使用 border-bottom 来实现的，hover 的时候改变背景色，单独看没有问题。

假如我的 md 语法如下，代码和超链接配合使用：

```md
[`Rollup configuration options pure`](https://rollupjs.org/configuration-options/#pure)
```

页面渲染如下图，代码背景盖住了下划线，hover 的时候也很奇怪。

![image](https://github.com/moeyua/astro-theme-typography/assets/47056890/8d76c918-7c4e-47b8-8224-63db3c2144da)

---

我建议通过如下方式实现：

![image](https://github.com/moeyua/astro-theme-typography/assets/47056890/23ab0186-285d-41c4-b467-3563df8d48b6)

并且 hover 的效果改为字体高亮或者添加阴影，而不是改变背景。

你认为呢？期待你的回复🙏

**Comment by moeyua** [comment]
抱歉最近工作较忙，没能及时回复。

超链接样式使用 `text-decroation` 确实要比 `border-bottom` 更加合理，我正在尝试对这部分样式进行替换。

关于超链接代码块我认为在 hover 时反色能够保持样式的一致性：

![Capture-2024-01-25-183904](https://github.com/moeyua/astro-theme-typography/assets/45156493/f0c72012-5eb1-45de-80b3-0091b9e05b53)
