### ISSUE TITLE
<建议> 关于页面功能的实现，按照文章的格式渲染一个markdown页面

### ISSUE THREAD

**Issue by suzulang** [moeyua/astro-theme-typography#44]
这个主题太爱了，实现了一下关于页面，渲染一个和文章风格类似的markdown页面
<img width="1437" alt="image" src="https://github.com/moeyua/astro-theme-typography/assets/155881657/b4aa01f6-6519-43d9-9328-a52f68cd7d48">
只需要编辑src/content/about/about.md即可
<img width="754" alt="image" src="https://github.com/moeyua/astro-theme-typography/assets/155881657/933719ee-214c-4a8c-86bb-70f941d44e1a">
需要提pr吗？还是说大佬有没有更好的实现方案？
期待大佬回复！

**Comment by moeyua** [comment]
感谢你的贡献和建议！

Astro 本身有渲染 markdown 文件作为页面的[功能](https://docs.astro.build/zh-cn/basics/astro-pages/#markdownmdx-%E9%A1%B5%E9%9D%A2)，只需要将 `about.md` 放入 `src/pages/` 即可，无需额外的处理。所以我认为不需要额外提供这个功能。再次感谢你的建议和贡献！

**Comment by suzulang** [comment]
> 感谢你的贡献和建议！
> 
> Astro 本身有渲染 markdown 文件作为页面的[功能](https://docs.astro.build/zh-cn/basics/astro-pages/#markdownmdx-%E9%A1%B5%E9%9D%A2)，只需要将 `about.md` 放入 `src/pages/` 即可，无需额外的处理。所以我认为不需要额外提供这个功能。再次感谢你的建议和贡献！

谢谢回复
好的，最近才接触astro，今天仔细学习了下，发现可以按照你说的，方便的进行配置。

**Comment by moeyua** [comment]
> > 感谢你的贡献和建议！
> > Astro 本身有渲染 markdown 文件作为页面的[功能](https://docs.astro.build/zh-cn/basics/astro-pages/#markdownmdx-%E9%A1%B5%E9%9D%A2)，只需要将 `about.md` 放入 `src/pages/` 即可，无需额外的处理。所以我认为不需要额外提供这个功能。再次感谢你的建议和贡献！
> 
> 我将 `about.md` 放入 `src/pages/ ` about页面没有出现md中的内容，是还需要配置什么吗 <img alt="image" width="398" src="https://private-user-images.githubusercontent.com/52907799/320910349-716a147b-f2cd-4d16-a7fc-ea795db583c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTI0NjgsIm5iZiI6MTcxMjcxMjE2OCwicGF0aCI6Ii81MjkwNzc5OS8zMjA5MTAzNDktNzE2YTE0N2ItZjJjZC00ZDE2LWE3ZmMtZWE3OTVkYjU4M2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAxMjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNmRkNjVmMDJmZmQ4ZTJkODU0NGM4ZDUxNGRmYzMyYzFiYjgwZjcwMGM3MzkwMzBjYWQyOWQ1NTM4N2FmN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KG-0tDxPs4GnvYPfZk4czVkEIfCtYmDjFVsCHpp2jxs">

需要先删除 `about.astro`，否则会优先渲染 `.astro` 文件

**Comment by datoou** [comment]
> > > 感谢你的贡献和建议！
> > > Astro 本身有渲染 markdown 文件作为页面的[功能](https://docs.astro.build/zh-cn/basics/astro-pages/#markdownmdx-%E9%A1%B5%E9%9D%A2)，只需要将 `about.md` 放入 `src/pages/` 即可，无需额外的处理。所以我认为不需要额外提供这个功能。再次感谢你的建议和贡献！
> > 
> > 
> > 我将 `about.md` 放入 `src/pages/ ` about页面没有出现md中的内容，是还需要配置什么吗 <img alt="image" width="398" src="https://private-user-images.githubusercontent.com/52907799/320910349-716a147b-f2cd-4d16-a7fc-ea795db583c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MTI0NjgsIm5iZiI6MTcxMjcxMjE2OCwicGF0aCI6Ii81MjkwNzc5OS8zMjA5MTAzNDktNzE2YTE0N2ItZjJjZC00ZDE2LWE3ZmMtZWE3OTVkYjU4M2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDAxMjI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNmRkNjVmMDJmZmQ4ZTJkODU0NGM4ZDUxNGRmYzMyYzFiYjgwZjcwMGM3MzkwMzBjYWQyOWQ1NTM4N2FmN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KG-0tDxPs4GnvYPfZk4czVkEIfCtYmDjFVsCHpp2jxs">
> 
> 需要先删除 `about.astro`，否则会优先渲染 `.astro` 文件

好的👌
