### ISSUE TITLE
<疑问/Feature>是否有设置文章排序的选项？

### ISSUE THREAD

**Issue by monsoir** [moeyua/astro-theme-typography#48]
发现文章的排序似乎是按照 `pubDate` 升序，不知道是否有相应的选项配置为降序呢？

如果没有，未知作者是否有闲添加该选项呢？

谢谢！

**Comment by suzulang** [comment]
> 发现文章的排序似乎是按照 `pubDate` 升序，不知道是否有相应的选项配置为降序呢？
> 
> 如果没有，未知作者是否有闲添加该选项呢？
> 
> 谢谢！

修改src/utils/index.ts代码
将
<img width="473" alt="image" src="https://github.com/moeyua/astro-theme-typography/assets/155881657/d5ee6890-eb60-497c-9a36-dd109dc38c8c">
改成
<img width="443" alt="image" src="https://github.com/moeyua/astro-theme-typography/assets/155881657/312db723-6238-4353-9d5b-f7db69235668">

即可实现降序

**Comment by moeyua** [comment]
我发现这似乎是我的一个疏漏，已在 #72 修复
