### ISSUE TITLE
[建议] 文章正文内容页面是否支持侧边栏标题导航

### ISSUE THREAD

**Issue by flyingcrp** [moeyua/astro-theme-typography#51]
长文时,分段的小标题有助于帮读者快速了解文章的结构和章节,而且可以快速的导航.
因此希望在文章内部支持章节导航.
例如这个[主题](https://astro-theme-cody.netlify.app/blog/markdown-style-guide/)的右侧.
感谢您提供如此优秀的主题.

**Comment by suzulang** [comment]
> 我觉得可以参考 **Anthony Fu** 的博客，不需要一直显示章节导航。 ![CleanShot 2024-04-02 at 23 06 47](https://private-user-images.githubusercontent.com/163419154/318840301-94309cf7-c17f-4662-b897-efa2b72d74a4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTYzOTAsIm5iZiI6MTcxMjQ1NjA5MCwicGF0aCI6Ii8xNjM0MTkxNTQvMzE4ODQwMzAxLTk0MzA5Y2Y3LWMxN2YtNDY2Mi1iODk3LWVmYTJiNzJkNzRhNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwMjE0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTg4MTEyMDcwNjJjZDI3NDIzOTQzY2RkNTU3ZDMwMTU4ZDBlOGI2M2NkN2FkZDkxYmMxMDI5NDkzZmQ0OWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-UagDatjzXVSobnRHBIs4GUdNxKkopR3eJdqr_QBUO4) [ ![CleanShot 2024-04-02 at 23 06 47](https://private-user-images.githubusercontent.com/163419154/318840301-94309cf7-c17f-4662-b897-efa2b72d74a4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTYzOTAsIm5iZiI6MTcxMjQ1NjA5MCwicGF0aCI6Ii8xNjM0MTkxNTQvMzE4ODQwMzAxLTk0MzA5Y2Y3LWMxN2YtNDY2Mi1iODk3LWVmYTJiNzJkNzRhNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwMjE0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTg4MTEyMDcwNjJjZDI3NDIzOTQzY2RkNTU3ZDMwMTU4ZDBlOGI2M2NkN2FkZDkxYmMxMDI5NDkzZmQ0OWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-UagDatjzXVSobnRHBIs4GUdNxKkopR3eJdqr_QBUO4) ](https://private-user-images.githubusercontent.com/163419154/318840301-94309cf7-c17f-4662-b897-efa2b72d74a4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTYzOTAsIm5iZiI6MTcxMjQ1NjA5MCwicGF0aCI6Ii8xNjM0MTkxNTQvMzE4ODQwMzAxLTk0MzA5Y2Y3LWMxN2YtNDY2Mi1iODk3LWVmYTJiNzJkNzRhNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwMjE0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTg4MTEyMDcwNjJjZDI3NDIzOTQzY2RkNTU3ZDMwMTU4ZDBlOGI2M2NkN2FkZDkxYmMxMDI5NDkzZmQ0OWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-UagDatjzXVSobnRHBIs4GUdNxKkopR3eJdqr_QBUO4) [ ](https://private-user-images.githubusercontent.com/163419154/318840301-94309cf7-c17f-4662-b897-efa2b72d74a4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NTYzOTAsIm5iZiI6MTcxMjQ1NjA5MCwicGF0aCI6Ii8xNjM0MTkxNTQvMzE4ODQwMzAxLTk0MzA5Y2Y3LWMxN2YtNDY2Mi1iODk3LWVmYTJiNzJkNzRhNC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwMjE0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTg4MTEyMDcwNjJjZDI3NDIzOTQzY2RkNTU3ZDMwMTU4ZDBlOGI2M2NkN2FkZDkxYmMxMDI5NDkzZmQ0OWFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-UagDatjzXVSobnRHBIs4GUdNxKkopR3eJdqr_QBUO4) Reference blog link：[https://antfu.me/posts/why-not-prettier-zh](url)

这个实现非常酷，请问有没有怎么实现这个的文章？

**Comment by moeyua** [comment]
这个功能涉及到对原始主题的改动较大，目前没有这个打算。如果有目录的需求可以参考[Astro 示例](https://docs.astro.build/zh-cn/guides/markdown-content/#%E6%A0%87%E9%A2%98-id-%E5%92%8C%E6%8F%92%E4%BB%B6)，或者如果有好的实现思路也欢迎补充💫

**Comment by rnotlnglgq** [comment]
LLM generated TOC component:
```
---
export interface Props {
  headings: Array<{ depth: number; slug: string; text: string }>
  title: string
}

const { headings, title } = Astro.props
---

<aside
  class="transition-swup-toc flex flex-col gap-2.5"
  m="7.5 lg:(x-0 t-20 b-4)"
  lg="row-1-2 col-1-2 justify-between items-start"
>
  <div class="sticky top-24">
    <div class="rounded-lg">
      <h2 class="text-lg font-bold mb-4 pl-4 border-l-2 border-primary">{title}</h2>
      <nav class="toc-container">
        <ul class="toc-list">
          {
            headings.map((heading) => (
              <li class={`toc-item depth-${heading.depth}`} style={`margin-left: ${(heading.depth - 1) * 0.75}rem`}>
                <a
                  href={`#${heading.slug}`}
                  class="toc-link hover:text-primary transition-colors"
                  data-heading-slug={heading.slug}
                >
                  {heading.text}
                </a>
              </li>
            ))
          }
        </ul>
      </nav>
    </div>
  </div>
</aside>

<style>
  .toc-container {
    max-height: calc(100vh - 12rem);
    overflow-y: auto;
    scrollbar-width: thin;
    scrollbar-color: var(--uno-colors-primary) transparent;
    padding-right: 1rem;
  }

  .toc-container::-webkit-scrollbar {
    width: 3px;
  }

  .toc-container::-webkit-scrollbar-track {
    background: transparent;
  }

  .toc-container::-webkit-scrollbar-thumb {
    background-color: var(--uno-colors-primary);
    border-radius: 3px;
  }

  .toc-list {
    position: relative;
  }

  .toc-item {
    line-height: 1.5;
    margin-bottom: 0.75rem;
    position: relative;
  }

  .toc-link {
    display: block;
    padding: 0.25rem 0.75rem;
    font-size: 0.95rem;
    color: var(--text-secondary);
    text-decoration: none;
    border-radius: 0.25rem;
    transition: all 0.2s ease;
    border-left: 2px solid transparent;
  }

  .toc-link:hover {
    color: var(--uno-colors-primary);
    background-color: color-mix(in srgb, var(--uno-colors-primary) 8%, transparent);
    border-left-color: var(--uno-colors-primary);
    text-decoration: none;
  }

  .toc-item.depth-1 {
    font-weight: 600;
    margin-top: 1rem;
  }

  .toc-item.depth-1:first-child {
    margin-top: 0;
  }

  .toc-item.depth-2 {
    font-weight: 500;
  }

  .toc-item.depth-3 {
    font-size: 0.9rem;
    color: var(--text-secondary);
  }

  .toc-item.depth-4,
  .toc-item.depth-5,
  .toc-item.depth-6 {
    font-size: 0.85rem;
    color: var(--text-secondary);
  }

  .toc-link[data-active='true'] {
    color: var(--uno-colors-primary);
    border-left-color: var(--uno-colors-primary);
    background-color: color-mix(in srgb, var(--uno-colors-primary) 8%, transparent);
  }

  /* Mobile TOC styles */
  @media (max-width: 768px) {
    .toc-container {
      max-height: 40vh;
      border-bottom: 1px solid rgba(var(--uno-colors-shadow), 0.2);
      margin-bottom: 1rem;
    }
  }
</style>

<script>
  document.documentElement.style.scrollBehavior = 'smooth'

  document.querySelectorAll('.toc-link').forEach((link) => {
    link.addEventListener('click', (e) => {
      // e.preventDefault()
      const href = (e.currentTarget as HTMLAnchorElement).getAttribute('href')
      if (href?.startsWith('#')) {
        const element = document.querySelector(href)
        if (element) {
          element.scrollIntoView({
            behavior: 'smooth',
            block: 'start',
            inline: 'nearest',
          })
          history.pushState(null, '', href)
        }
      }
    })
  })
</script>
```
In `LayoutDefault.astro`, add an column and adjust geometry:
```
  <body
    class="h-100vh max-w-1200px min-w-390px mx-a"
    p="7.5 lg:(y-0 x-20)"
    lg="grid gap-x-6 cols-[1fr_3fr_1fr] rows-[1fr_9rem]"
  >
    <slot name="toc" />

    <header
      class="transition-swup-header flex flex-col gap-2.5"
      m="7.5 lg:(x-0 t-20 b-4)"
      lg="row-1-2 col-3-4 justify-between items-start"
    >
      <SiteTitle />
      <SiteNavigation />
    </header>

    <main class="transition-swup-main overflow-y-scroll scrollbar-hide outline-none" lg="row-1-3 col-2-3 py-20">
      <slot />
    </main>

    <footer class="transition-swup-footer py-7.5" lg="row-2-3 col-3-4">
      <SiteFooter />
    </footer>
```
Then use this component in `[...id].astro`:
```
import TableOfContents from '~/components/TableOfContents.astro'
const { Content, headings } = await render(entry)
<TableOfContents slot="toc" headings={headings} title={t('table_of_contents')} />
```
Also encapsule the main article components in a `<main>` element. Then update the `container` field if you are using swup cache(yes by default in this template).
