### ISSUE TITLE
Add a comment section

### ISSUE THREAD

**Issue by suzulang** [moeyua/astro-theme-typography#54]
## 我的实现

参考官网上的添加评论模块的实现，给自己的博客已经实现了评论功能，利用giscus
<img width="945" alt="image" src="https://github.com/moeyua/astro-theme-typography/assets/155881657/78836ea4-a5f9-4227-91ec-054e2dd37804">

### 英文文档

<img width="316" alt="image" src="https://github.com/moeyua/astro-theme-typography/assets/155881657/98e41045-fd8f-4ddf-a46d-1c67a2bfe6f8">

这里article直接指向了官方文档

---

### 中文文档

<img width="242" alt="image" src="https://github.com/moeyua/astro-theme-typography/assets/155881657/8db8bb70-5e0a-4646-b8ed-767a7ee7ea0a">

**这个文章超链接，我打算指向我博客的文章，因为官网的文档只提供了英文版本，我打算写一个更加通俗易懂的中文版本。没有直接翻译是因为，我要进行截图，上传到图床，我怕出现版权之类的问题**

大佬有没有什么建议？

是建议我把这两篇文章精简一下，写在当前项目的README.md的方式来实现，还是说用超链接的方式来实现？

**Comment by moeyua** [comment]
评论功能目前的计划是提供多个服务，用户只需提供 id 即可开启，但是还不确定如何将相关服务的配置项暴露给用户

**Comment by suzulang** [comment]
> 评论功能目前的计划是提供多个服务，用户只需提供 id 即可开启，但是还不确定如何将相关服务的配置项暴露给用户

我看了几款开源的
- giscus
- https://github.com/twikoojs/twikoo
仅供参考

**Comment by moeyua** [comment]
感谢你的建议，评论功能已添加，具体可以查看 #61 

<img width="946" alt="image" src="https://github.com/moeyua/astro-theme-typography/assets/45156493/a2a8d77b-44b9-4cc2-97c7-d1b8ec0842a1">
