### ISSUE TITLE
Added support for MDX files

### ISSUE THREAD

**Issue by EvansMusk** [moeyua/astro-theme-typography#58]
My Realization
---
![CleanShot 2024-04-05 at 00 31 14@2x](https://github.com/moeyua/astro-theme-typography/assets/163419154/513808e1-cdca-4a7b-b84e-668714a9f394)

Modify Script： [https://github.com/EvansMusk/Paper/blob/main/scripts/new-mdx.sh](url)
Adding common components：[https://github.com/EvansMusk/Paper/blob/main/src/components/Prompt.astro](url)

**Comment by moeyua** [comment]
感谢你的建议，new post 脚本进行了重构，支持 mdx 的创建， #67
