### ISSUE TITLE
替换图标大小变化

### ISSUE THREAD

**Issue by hhwjsw711** [moeyua/astro-theme-typography#93]
在原来的 GitHub、RSS、Twitter 图标大小均为 19.2x19.2，但是我尝试参考ReadMe通过YouTube、WeChat等去做替换，发现大小变成了 4x4，在页面上显示未一个小点，不清楚是哪里的问题？

**Comment by moeyua** [comment]
有尝试过重新启动开发服务器吗，新增的图标需要重新打包后才可以被包含在内。

**Comment by hhwjsw711** [comment]
我刚刚测试了下，是的，重新运行后就正常了，感谢！

**Comment by moeyua** [comment]
不客气哦
